FROM golang:1.24-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" \
    -o /evidra ./cmd/evidra

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /evidra /usr/local/bin/evidra
ENTRYPOINT ["/usr/local/bin/evidra"]
